name: kyrios

on: push

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Inject Dockerfile
        uses: docker://ryanlime/kyriosctl:v0.0.42
        with:
          args: docker inject -lgolang
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/${{ github.repository_owner  }}/example-golang # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  deploy:
    name: Deploy with GitOps
    env:
      SHORT_SHA: ${GITHUB_SHA::7}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout Gitops code
        uses: actions/checkout@v2
        with:
          repository: kyriosproj/example-golang-gitops
      - name: Update yaml
        uses: docker://ryanlime/kyriosctl:v0.0.42
        with:
          args: gitops updateTag -t sha-${{ steps.slug.outputs.sha7 }}
      - name: Commit files
        run: |
          git config --local user.email "ryan@ryanli.me"
          git config --local user.name "Kyrios Bot"
          git commit -a -m "[release][dev] ${{ steps.slug.outputs.sha7 }}" -m "{{workflow.parameters.commit_url}}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}



